I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 132, in script
    call screen train1()
  File "renpy/common/000statements.rpy", line 569, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
TypeError: 'int' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 132, in script
    call screen train1()
  File "renpy/ast.py", line 2009, in execute
    self.call("execute")
  File "renpy/ast.py", line 1997, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 569, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "renpy/exports.py", line 3057, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3276, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3633, in interact_core
    new_widget=layers_root)
TypeError: 'int' object is not callable

Windows-10-10.0.19041
Ren'Py 7.4.6.1693
CGJ2021 1.0
Sun Jul 11 00:35:14 2021
